# default values
ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0
MIRROR_FLIP_OPTIONS = ['upright', 'mirror', 'flip', 'mirror&flip']
BLUR_DEFAULT = 0
EFFECT_OPTIONS = ['None', 'Emboss', 'Find edges', 'Contour', 'Edge enhance']
BRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
CONTRAST_DEFAULT = 1
GRAYSCALE_DEFAULT = False
INVERT_DEFAULT = False
# Colors
BACKGROUND_COLOUR = '#242424'
WHITE = '#FFF'
GREY = 'grey'
BLUE = '#1f6aa5'
DARK_GREY = '#4a4a4a'
MID_GREY = '#3a3a3a'
CLOSE_RED = '#8a0606'
SLIDER_BG = '#646864'
DROPDOWN_MAIN_COLOUR = '#444'
DROPDOWN_BUTTON_COLOUR = '#555'
DROPDOWN_HOVER_COLOUR = '#333'
DROPDOWN_MENU_COLOUR = '#666'
