import types
from collections.abc import Generator
from contextlib import contextmanager

from _moderngl import Attribute as Attribute
from _moderngl import Error as Error
from _moderngl import InvalidObject as InvalidObject
from _moderngl import StorageBlock as StorageBlock
from _moderngl import Subroutine as Subroutine
from _moderngl import Uniform as Uniform
from _moderngl import UniformBlock as UniformBlock
from _moderngl import Varying as Varying
from _typeshed import Incomplete
from moderngl import mgl as mgl

__version__: str

def packager_imports() -> None: ...

class _store:
    default_context: Incomplete

class Buffer:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def size(self): ...
    @property
    def dynamic(self): ...
    @property
    def glo(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def write(self, data, offset: int = 0) -> None: ...
    def write_chunks(self, data, start, step, count) -> None: ...
    def read(self, size: int = -1, offset: int = 0): ...
    def read_into(self, buffer, size: int = -1, offset: int = 0, write_offset: int = 0): ...
    def read_chunks(self, chunk_size, start, step, count): ...
    def read_chunks_into(self, buffer, chunk_size, start, step, count, write_offset: int = 0): ...
    def clear(self, size: int = -1, offset: int = 0, chunk=None) -> None: ...
    def bind_to_uniform_block(self, binding: int = 0, offset: int = 0, size: int = -1) -> None: ...
    def bind_to_storage_buffer(
        self, binding: int = 0, offset: int = 0, size: int = -1
    ) -> None: ...
    def orphan(self, size: int = -1) -> None: ...
    def release(self) -> None: ...
    def bind(self, *attribs, layout=None): ...
    def assign(self, index): ...

class ConditionalRender:
    mglo: Incomplete
    def __init__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args) -> None: ...

class Query:
    mglo: Incomplete
    crender: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args) -> None: ...
    @property
    def samples(self): ...
    @property
    def primitives(self): ...
    @property
    def elapsed(self): ...

class ComputeShader:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __iter__(self): ...
    @property
    def glo(self): ...
    def run(self, group_x: int = 1, group_y: int = 1, group_z: int = 1): ...
    def run_indirect(self, buffer, offset: int = 0): ...
    def get(self, key, default): ...
    def release(self) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...

class Framebuffer:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def viewport(self): ...
    @viewport.setter
    def viewport(self, value) -> None: ...
    @property
    def scissor(self): ...
    @scissor.setter
    def scissor(self, value) -> None: ...
    @property
    def color_mask(self): ...
    @color_mask.setter
    def color_mask(self, value) -> None: ...
    @property
    def depth_mask(self): ...
    @depth_mask.setter
    def depth_mask(self, value) -> None: ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    @property
    def size(self): ...
    @property
    def samples(self): ...
    @property
    def bits(self): ...
    @property
    def color_attachments(self): ...
    @property
    def depth_attachment(self): ...
    @property
    def glo(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def clear(
        self,
        red: float = 0.0,
        green: float = 0.0,
        blue: float = 0.0,
        alpha: float = 0.0,
        depth: float = 1.0,
        viewport=None,
        color=None,
    ) -> None: ...
    def use(self) -> None: ...
    def read(
        self,
        viewport=None,
        components: int = 3,
        attachment: int = 0,
        alignment: int = 1,
        dtype: str = "f1",
        clamp: bool = False,
    ): ...
    def read_into(
        self,
        buffer,
        viewport=None,
        components: int = 3,
        attachment: int = 0,
        alignment: int = 1,
        dtype: str = "f1",
        clamp: bool = False,
        write_offset: int = 0,
    ): ...
    def release(self) -> None: ...

class Program:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __iter__(self): ...
    @property
    def is_transform(self): ...
    @property
    def geometry_input(self): ...
    @property
    def geometry_output(self): ...
    @property
    def geometry_vertices(self): ...
    @property
    def subroutines(self): ...
    @property
    def glo(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def get(self, key, default): ...
    def release(self) -> None: ...

class Renderbuffer:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    @property
    def size(self): ...
    @property
    def samples(self): ...
    @property
    def components(self): ...
    @property
    def depth(self): ...
    @property
    def dtype(self): ...
    @property
    def glo(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def release(self) -> None: ...

class Sampler:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    texture: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def use(self, location: int = 0) -> None: ...
    def clear(self, location: int = 0) -> None: ...
    def release(self) -> None: ...
    @property
    def repeat_x(self): ...
    @repeat_x.setter
    def repeat_x(self, value) -> None: ...
    @property
    def repeat_y(self): ...
    @repeat_y.setter
    def repeat_y(self, value) -> None: ...
    @property
    def repeat_z(self): ...
    @repeat_z.setter
    def repeat_z(self, value) -> None: ...
    @property
    def filter(self): ...
    @filter.setter
    def filter(self, value) -> None: ...
    @property
    def compare_func(self): ...
    @compare_func.setter
    def compare_func(self, value) -> None: ...
    @property
    def anisotropy(self): ...
    @anisotropy.setter
    def anisotropy(self, value) -> None: ...
    @property
    def border_color(self): ...
    @border_color.setter
    def border_color(self, value) -> None: ...
    @property
    def min_lod(self): ...
    @min_lod.setter
    def min_lod(self, value) -> None: ...
    @property
    def max_lod(self): ...
    @max_lod.setter
    def max_lod(self, value) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def assign(self, index): ...

class Scope:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args) -> None: ...
    def __del__(self) -> None: ...
    def release(self) -> None: ...

class Texture:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def repeat_x(self): ...
    @repeat_x.setter
    def repeat_x(self, value) -> None: ...
    @property
    def repeat_y(self): ...
    @repeat_y.setter
    def repeat_y(self, value) -> None: ...
    @property
    def filter(self): ...
    @filter.setter
    def filter(self, value) -> None: ...
    @property
    def anisotropy(self): ...
    @anisotropy.setter
    def anisotropy(self, value) -> None: ...
    @property
    def swizzle(self): ...
    @swizzle.setter
    def swizzle(self, value) -> None: ...
    @property
    def compare_func(self): ...
    @compare_func.setter
    def compare_func(self, value) -> None: ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    @property
    def size(self): ...
    @property
    def components(self): ...
    @property
    def samples(self): ...
    @property
    def dtype(self): ...
    @property
    def depth(self): ...
    @property
    def glo(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def read(self, level: int = 0, alignment: int = 1): ...
    def read_into(self, buffer, level: int = 0, alignment: int = 1, write_offset: int = 0): ...
    def write(self, data, viewport=None, level: int = 0, alignment: int = 1) -> None: ...
    def build_mipmaps(self, base: int = 0, max_level: int = 1000) -> None: ...
    def use(self, location: int = 0) -> None: ...
    def bind_to_image(
        self, unit, read: bool = True, write: bool = True, level: int = 0, format: int = 0
    ) -> None: ...
    def get_handle(self, resident: bool = True): ...
    def release(self) -> None: ...

class Texture3D:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def repeat_x(self): ...
    @repeat_x.setter
    def repeat_x(self, value) -> None: ...
    @property
    def repeat_y(self): ...
    @repeat_y.setter
    def repeat_y(self, value) -> None: ...
    @property
    def repeat_z(self): ...
    @repeat_z.setter
    def repeat_z(self, value) -> None: ...
    @property
    def filter(self): ...
    @filter.setter
    def filter(self, value) -> None: ...
    @property
    def swizzle(self): ...
    @swizzle.setter
    def swizzle(self, value) -> None: ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    @property
    def depth(self): ...
    @property
    def size(self): ...
    @property
    def components(self): ...
    @property
    def dtype(self): ...
    @property
    def glo(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def read(self, alignment: int = 1): ...
    def read_into(self, buffer, alignment: int = 1, write_offset: int = 0): ...
    def write(self, data, viewport=None, alignment: int = 1) -> None: ...
    def build_mipmaps(self, base: int = 0, max_level: int = 1000) -> None: ...
    def use(self, location: int = 0) -> None: ...
    def bind_to_image(
        self, unit, read: bool = True, write: bool = True, level: int = 0, format: int = 0
    ) -> None: ...
    def get_handle(self, resident: bool = True): ...
    def release(self) -> None: ...

class TextureCube:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def size(self): ...
    @property
    def components(self): ...
    @property
    def dtype(self): ...
    @property
    def filter(self): ...
    @filter.setter
    def filter(self, value) -> None: ...
    @property
    def swizzle(self): ...
    @swizzle.setter
    def swizzle(self, value) -> None: ...
    @property
    def compare_func(self): ...
    @compare_func.setter
    def compare_func(self, value) -> None: ...
    @property
    def anisotropy(self): ...
    @anisotropy.setter
    def anisotropy(self, value) -> None: ...
    @property
    def depth(self): ...
    @property
    def glo(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def read(self, face, alignment: int = 1): ...
    def read_into(self, buffer, face, alignment: int = 1, write_offset: int = 0): ...
    def write(self, face, data, viewport=None, alignment: int = 1) -> None: ...
    def build_mipmaps(self, base: int = 0, max_level: int = 1000) -> None: ...
    def use(self, location: int = 0) -> None: ...
    def bind_to_image(
        self, unit, read: bool = True, write: bool = True, level: int = 0, format: int = 0
    ) -> None: ...
    def get_handle(self, resident: bool = True): ...
    def release(self) -> None: ...

class TextureArray:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def repeat_x(self): ...
    @repeat_x.setter
    def repeat_x(self, value) -> None: ...
    @property
    def repeat_y(self): ...
    @repeat_y.setter
    def repeat_y(self, value) -> None: ...
    @property
    def filter(self): ...
    @filter.setter
    def filter(self, value) -> None: ...
    @property
    def swizzle(self): ...
    @swizzle.setter
    def swizzle(self, value) -> None: ...
    @property
    def anisotropy(self): ...
    @anisotropy.setter
    def anisotropy(self, value) -> None: ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    @property
    def layers(self): ...
    @property
    def size(self): ...
    @property
    def components(self): ...
    @property
    def dtype(self): ...
    @property
    def glo(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def read(self, alignment: int = 1): ...
    def read_into(self, buffer, alignment: int = 1, write_offset: int = 0): ...
    def write(self, data, viewport=None, alignment: int = 1) -> None: ...
    def build_mipmaps(self, base: int = 0, max_level: int = 1000) -> None: ...
    def use(self, location: int = 0) -> None: ...
    def bind_to_image(
        self, unit, read: bool = True, write: bool = True, level: int = 0, format: int = 0
    ) -> None: ...
    def get_handle(self, resident: bool = True): ...
    def release(self) -> None: ...

class VertexArray:
    mglo: Incomplete
    ctx: Incomplete
    extra: Incomplete
    scope: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def mode(self): ...
    @mode.setter
    def mode(self, value) -> None: ...
    @property
    def program(self): ...
    @property
    def index_buffer(self): ...
    @property
    def index_element_size(self): ...
    @property
    def vertices(self): ...
    @vertices.setter
    def vertices(self, value) -> None: ...
    @property
    def instances(self): ...
    @instances.setter
    def instances(self, value) -> None: ...
    @property
    def subroutines(self): ...
    @subroutines.setter
    def subroutines(self, value) -> None: ...
    @property
    def glo(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, value) -> None: ...
    def render(
        self, mode=None, vertices: int = -1, first: int = 0, instances: int = -1
    ) -> None: ...
    def render_indirect(self, buffer, mode=None, count: int = -1, first: int = 0) -> None: ...
    def transform(
        self,
        buffer,
        mode=None,
        vertices: int = -1,
        first: int = 0,
        instances: int = -1,
        buffer_offset: int = 0,
    ) -> None: ...
    def bind(
        self,
        attribute,
        cls,
        buffer,
        fmt,
        offset: int = 0,
        stride: int = 0,
        divisor: int = 0,
        normalize: bool = False,
    ) -> None: ...
    def release(self) -> None: ...

class Context:
    NOTHING: int
    BLEND: int
    DEPTH_TEST: int
    CULL_FACE: int
    RASTERIZER_DISCARD: int
    PROGRAM_POINT_SIZE: int
    POINTS: int
    LINES: int
    LINE_LOOP: int
    LINE_STRIP: int
    TRIANGLES: int
    TRIANGLE_STRIP: int
    TRIANGLE_FAN: int
    LINES_ADJACENCY: int
    LINE_STRIP_ADJACENCY: int
    TRIANGLES_ADJACENCY: int
    TRIANGLE_STRIP_ADJACENCY: int
    PATCHES: int
    NEAREST: int
    LINEAR: int
    NEAREST_MIPMAP_NEAREST: int
    LINEAR_MIPMAP_NEAREST: int
    NEAREST_MIPMAP_LINEAR: int
    LINEAR_MIPMAP_LINEAR: int
    ZERO: int
    ONE: int
    SRC_COLOR: int
    ONE_MINUS_SRC_COLOR: int
    SRC_ALPHA: int
    ONE_MINUS_SRC_ALPHA: int
    DST_ALPHA: int
    ONE_MINUS_DST_ALPHA: int
    DST_COLOR: int
    ONE_MINUS_DST_COLOR: int
    DEFAULT_BLENDING: Incomplete
    ADDITIVE_BLENDING: Incomplete
    PREMULTIPLIED_ALPHA: Incomplete
    FUNC_ADD: int
    FUNC_SUBTRACT: int
    FUNC_REVERSE_SUBTRACT: int
    MIN: int
    MAX: int
    FIRST_VERTEX_CONVENTION: int
    LAST_VERTEX_CONVENTION: int
    VERTEX_ATTRIB_ARRAY_BARRIER_BIT: int
    ELEMENT_ARRAY_BARRIER_BIT: int
    UNIFORM_BARRIER_BIT: int
    TEXTURE_FETCH_BARRIER_BIT: int
    SHADER_IMAGE_ACCESS_BARRIER_BIT: int
    COMMAND_BARRIER_BIT: int
    PIXEL_BUFFER_BARRIER_BIT: int
    TEXTURE_UPDATE_BARRIER_BIT: int
    BUFFER_UPDATE_BARRIER_BIT: int
    FRAMEBUFFER_BARRIER_BIT: int
    TRANSFORM_FEEDBACK_BARRIER_BIT: int
    ATOMIC_COUNTER_BARRIER_BIT: int
    SHADER_STORAGE_BARRIER_BIT: int
    ALL_BARRIER_BITS: int
    mglo: Incomplete
    version_code: Incomplete
    fbo: Incomplete
    extra: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    @property
    def gc_mode(self): ...
    @gc_mode.setter
    def gc_mode(self, value) -> None: ...
    @property
    def objects(self): ...
    def gc(self): ...
    @property
    def line_width(self): ...
    @line_width.setter
    def line_width(self, value) -> None: ...
    @property
    def point_size(self): ...
    @point_size.setter
    def point_size(self, value) -> None: ...
    @property
    def depth_func(self) -> None: ...
    @depth_func.setter
    def depth_func(self, value) -> None: ...
    @property
    def blend_func(self) -> None: ...
    @blend_func.setter
    def blend_func(self, value) -> None: ...
    @property
    def blend_equation(self) -> None: ...
    @blend_equation.setter
    def blend_equation(self, value) -> None: ...
    @property
    def depth_clamp_range(self) -> None: ...
    @depth_clamp_range.setter
    def depth_clamp_range(self, value) -> None: ...
    @property
    def multisample(self) -> None: ...
    @multisample.setter
    def multisample(self, value) -> None: ...
    @property
    def provoking_vertex(self) -> None: ...
    @provoking_vertex.setter
    def provoking_vertex(self, value) -> None: ...
    @property
    def polygon_offset(self): ...
    @polygon_offset.setter
    def polygon_offset(self, value) -> None: ...
    @property
    def viewport(self): ...
    @viewport.setter
    def viewport(self, value) -> None: ...
    @property
    def scissor(self): ...
    @scissor.setter
    def scissor(self, value) -> None: ...
    @property
    def max_samples(self): ...
    @property
    def max_integer_samples(self): ...
    @property
    def max_texture_units(self): ...
    @property
    def max_label_length(self): ...
    @property
    def max_debug_message_length(self): ...
    @property
    def max_debug_group_stack_depth(self): ...
    @property
    def default_texture_unit(self): ...
    @default_texture_unit.setter
    def default_texture_unit(self, value) -> None: ...
    @property
    def max_anisotropy(self): ...
    @property
    def screen(self): ...
    @property
    def wireframe(self): ...
    @wireframe.setter
    def wireframe(self, value) -> None: ...
    @property
    def front_face(self): ...
    @front_face.setter
    def front_face(self, value) -> None: ...
    @property
    def cull_face(self): ...
    @cull_face.setter
    def cull_face(self, value) -> None: ...
    @property
    def patch_vertices(self): ...
    @patch_vertices.setter
    def patch_vertices(self, value) -> None: ...
    @property
    def error(self): ...
    @property
    def extensions(self): ...
    @property
    def supports_labels(self): ...
    @property
    def supports_debug_scopes(self): ...
    @property
    def info(self): ...
    @property
    def includes(self): ...
    def clear(
        self,
        red: float = 0.0,
        green: float = 0.0,
        blue: float = 0.0,
        alpha: float = 0.0,
        depth: float = 1.0,
        viewport=None,
        color=None,
    ) -> None: ...
    def enable_only(self, flags) -> None: ...
    def enable(self, flags) -> None: ...
    def disable(self, flags) -> None: ...
    def enable_direct(self, enum) -> None: ...
    def disable_direct(self, enum) -> None: ...
    def finish(self) -> None: ...
    def copy_buffer(
        self, dst: Buffer, src: Buffer, size: int = -1, read_offset: int = 0, write_offset: int = 0
    ): ...
    def copy_framebuffer(self, dst, src) -> None: ...
    def detect_framebuffer(self, glo=None): ...
    def buffer(self, data=None, reserve: int = 0, dynamic: bool = False): ...
    def external_buffer(self, glo, size): ...
    def external_texture(self, glo, size, components, samples, dtype): ...
    def texture(
        self,
        size,
        components,
        data=None,
        samples: int = 0,
        alignment: int = 1,
        dtype: str = "f1",
        internal_format=None,
        renderbuffer: bool = False,
    ): ...
    def texture_array(
        self, size, components, data=None, alignment: int = 1, dtype: str = "f1"
    ): ...
    def texture3d(self, size, components, data=None, alignment: int = 1, dtype: str = "f1"): ...
    def texture_cube(
        self,
        size,
        components,
        data=None,
        alignment: int = 1,
        dtype: str = "f1",
        internal_format=None,
    ): ...
    def depth_texture(
        self, size, data=None, samples: int = 0, alignment: int = 4, renderbuffer: bool = False
    ): ...
    def depth_texture_cube(self, size, data=None, alignment: int = 4): ...
    def vertex_array(self, *args, **kwargs): ...
    def simple_vertex_array(
        self,
        program,
        buffer,
        *attributes,
        index_buffer=None,
        index_element_size: int = 4,
        mode=None,
    ): ...
    def program(
        self,
        vertex_shader=None,
        fragment_shader=None,
        geometry_shader=None,
        tess_control_shader=None,
        tess_evaluation_shader=None,
        varyings=(),
        fragment_outputs=None,
        attributes=None,
        varyings_capture_mode: str = "interleaved",
    ): ...
    def query(
        self,
        samples: bool = False,
        any_samples: bool = False,
        time: bool = False,
        primitives: bool = False,
    ): ...
    def scope(
        self,
        framebuffer=None,
        enable_only=None,
        textures=(),
        uniform_buffers=(),
        storage_buffers=(),
        samplers=(),
        enable=None,
    ): ...
    def simple_framebuffer(
        self, size, components: int = 4, samples: int = 0, dtype: str = "f1"
    ): ...
    def framebuffer(self, color_attachments=(), depth_attachment=None): ...
    def empty_framebuffer(self, size, layers: int = 0, samples: int = 0): ...
    def renderbuffer(self, size, components: int = 4, samples: int = 0, dtype: str = "f1"): ...
    def depth_renderbuffer(self, size, samples: int = 0): ...
    def compute_shader(self, source): ...
    def sampler(
        self,
        repeat_x: bool = True,
        repeat_y: bool = True,
        repeat_z: bool = True,
        filter=None,
        anisotropy: float = 1.0,
        compare_func: str = "?",
        border_color=None,
        min_lod: float = -1000.0,
        max_lod: float = 1000.0,
        texture=None,
    ): ...
    def memory_barrier(self, barriers=..., by_region: bool = False) -> None: ...
    def clear_samplers(self, start: int = 0, end: int = -1) -> None: ...
    def core_profile_check(self) -> None: ...
    def __enter__(self): ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: types.TracebackType | None,
    ) -> None: ...
    def release(self) -> None: ...
    def clear_errors(self) -> None: ...
    @contextmanager
    def debug_scope(
        self, label, group_id=None, source: str = "application"
    ) -> Generator[None]: ...

def create_context(require=None, standalone: bool = False, share: bool = False, **settings): ...
def init_context(loader=None) -> None: ...
def get_context(): ...
def create_standalone_context(**kwargs): ...
def detect_format(program, attributes, mode: str = "mgl"): ...
