from _moderngl import InvalidObject as InvalidObject

def create_context(*args, **kwargs): ...
def expected_size(*args, **kwargs): ...
def strsize(*args, **kwargs): ...
def writable_bytes(*args, **kwargs): ...
